[versions]
accompanistDrawablepainter = "0.37.3"
agp = "8.13.2"
app = "1.7.0"
googleGenai = "1.11.0"
googlePlayServicesCast = "21.5.0"
amplituda = "2.3.0"
animation = "1.8.1"
appcompat = "1.7.0"
capturable = "3.0.1"
codeview = "1.3.9"
coilCompose = "2.7.0"
composeAudiowaveform = "1.1.2"
composeDnd = "0.3.0"
constraintlayoutCompose = "1.1.1"
coreSplashscreen = "1.0.1"
desugarJdkLibs = "2.1.4"
duktapeAndroid = "1.3.0"
foundation = "1.8.1"
glance = "1.2.0-rc01"
graphicsShapes = "1.1.0"
gson = "2.11.0"
hiltAndroid = "2.53.1"
hiltNavigationCompose = "1.2.0"
ktor = "2.3.12"
kotlin = "2.1.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
kotlinx-coroutines = "1.8.0"
kotlinxCollectionsImmutable = "0.3.7"
kotlinxSerializationJson = "1.8.0"
lifecycleRuntimeKtx = "2.9.0"
activityCompose = "1.10.1"
composeBom = "2025.05.00"
material = "1.13.0"
material3 = "1.5.0-alpha10"
media = "1.7.1"
media3Session = "1.8.0"
media3Transformer = "1.8.0"
mediaRouter = "1.7.0"
navigationCompose = "2.9.6"
paletteKtx = "1.0.0"
protobufJavalite = "3.25.1"
pytorch_android = "2.1.0"
pytorch_android_torchvision = "2.1.0"
reorderable = "0.9.6"
reorderables = "2.5.1"
roomCompiler = "2.7.1"
roomKtx = "2.7.1"
roomRuntime = "2.7.1"
accompanist = "0.37.3"
checkerframework = "3.49.5" # O la versión más reciente que encuentres
taglib = "1.0.5"

# DI
dagger = "2.53.1"
javax-inject = "1"

# Annotations procesing
ksp = "2.1.0-1.0.29"
smoothCornerRectAndroidCompose = "v1.0.0"
spleeterAndroidIos = "1.0.2"
tensorflowLite = "2.17.0"
tensorflowLiteSelectTfOps = "2.16.1"
tensorflowLiteSelectTfOpsVersion = "2.16.1"
tensorflowLiteSupport = "0.5.0"
wavySlider = "2.0.0"
workRuntimeKtx = "2.10.1"
composeTesting = "1.0.0-alpha03"
timber = "5.0.1"
generativeai = "0.9.0"

retrofit = "3.0.0"
okhttp = "5.1.0"
mediarouterVersion = "1.8.1"
playServicesCastFramework = "22.2.0"
navigationRuntimeKtx = "2.9.6"
material3Version = "1.4.0"

[libraries]
accompanist-drawablepainter = { module = "com.google.accompanist:accompanist-drawablepainter", version.ref = "accompanistDrawablepainter" }
androidx-app = { module = "androidx.car.app:app", version.ref = "app" }
androidx-app-projected = { module = "androidx.car.app:app-projected", version.ref = "app" }
androidx-media = { module = "androidx.media:media", version.ref = "media" }
androidx-ui-text-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts" }
google-genai = { group = "com.google.genai", name = "google-genai", version.ref = "googleGenai" }
google-play-services-cast-framework = { group = "com.google.android.gms", name = "play-services-cast-framework", version.ref = "googlePlayServicesCast" }
amplituda = { module = "com.github.lincollincol:amplituda", version.ref = "amplituda" }
androidx-animation = { module = "androidx.compose.animation:animation", version.ref = "animation" }
desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdkLibs" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
androidx-glance = { module = "androidx.glance:glance", version.ref = "glance" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glance" }
androidx-graphics-shapes = { module = "androidx.graphics:graphics-shapes", version.ref = "graphicsShapes" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltNavigationCompose" }
androidx-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Session" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "media3Session" }
androidx-media3-transformer = { module = "androidx.media3:media3-transformer", version.ref = "media3Transformer" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Session" }
androidx-media3-exoplayer-ffmpeg = { module = "org.jellyfin.media3:media3-ffmpeg-decoder", version = "1.8.0+1" }
androidx-media-router = { module = "androidx.mediarouter:mediarouter", version.ref = "mediaRouter" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "paletteKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
capturable = { module = "dev.shreyaspatil:capturable", version.ref = "capturable" }
codeview = { module = "io.github.amrdeveloper:codeview", version.ref = "codeview" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
compose-audiowaveform = { module = "com.github.lincollincol:compose-audiowaveform", version.ref = "composeAudiowaveform" }
compose-dnd = { module = "com.mohamedrejeb.dnd:compose-dnd", version.ref = "composeDnd" }
duktape-android = { module = "com.squareup.duktape:duktape-android", version.ref = "duktapeAndroid" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltNavigationCompose" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-server-core = { group = "io.ktor", name = "ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty-jvm", version.ref = "ktor" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobufJavalite" }
pytorch_android = { module = "org.pytorch:pytorch_android", version.ref = "pytorch_android" }
pytorch_android_torchvision = { module = "org.pytorch:pytorch_android_torchvision", version.ref = "pytorch_android_torchvision" }
reorderable = { module = "org.burnoutcrew.composereorderable:reorderable", version.ref = "reorderable" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
smooth-corner-rect-android-compose = { module = "com.github.racra:smooth-corner-rect-android-compose", version.ref = "smoothCornerRectAndroidCompose" }
spleeter-android-ios = { module = "com.github.FaceOnLive:Spleeter-Android-iOS", version.ref = "spleeterAndroidIos" }
tensorflow-lite = { module = "org.tensorflow:tensorflow-lite", version.ref = "tensorflowLite" }
#tensorflow-lite-select-tf-ops = { module = "org.tensorflow:tensorflow-lite-select-tf-ops", version.ref = "tensorflowLiteSelectTfOps" }
tensorflow-lite-select-tf-ops = { module = "org.tensorflow:tensorflow-lite-select-tf-ops", version.ref = "tensorflowLiteSelectTfOpsVersion" }
tensorflow-lite-support = { module = "org.tensorflow:tensorflow-lite-support", version.ref = "tensorflowLiteSupport" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
wavy-slider = { module = "ir.mahozad.multiplatform:wavy-slider", version.ref = "wavySlider" }
checker-qual = { group = "org.checkerframework", name = "checker-qual", version.ref = "checkerframework" }
taglib = { group = "io.github.kyant0", name = "taglib", version.ref = "taglib" }
reorderables = { group = "sh.calvin.reorderable", name = "reorderable", version.ref = "reorderables" }
generativeai = { group = "com.google.ai.client.generativeai", name = "generativeai", version.ref = "generativeai" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
androidx-mediarouter = { group = "androidx.mediarouter", name = "mediarouter", version.ref = "mediarouterVersion" }
play-services-cast-framework = { group = "com.google.android.gms", name = "play-services-cast-framework", version.ref = "playServicesCastFramework" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3Version" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version = "2.1.0" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin"}

dagger-hilt-android = { id = "com.google.dagger.hilt.android" , version.ref = "dagger" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}

